from __future__ import annotations

from datetime import datetime, timedelta
from typing import Dict, List

from data import destinations_by_name


def _hours_ago(hours: float) -> str:
    return (datetime.now() - timedelta(hours=hours)).replace(microsecond=0).isoformat()


def _incident(
    incident_id: str,
    incident_type: str,
    latitude: float,
    longitude: float,
    severity: int,
    description: str,
    hours_ago: float,
    verified: bool,
    similar_reports: int = 0,
    scenario_tag: str = "scenario",
) -> Dict[str, object]:
    return {
        "id": incident_id,
        "incident_type": incident_type,
        "latitude": latitude,
        "longitude": longitude,
        "severity": severity,
        "description": description,
        "timestamp": _hours_ago(hours_ago),
        "verified": verified,
        "similar_reports": similar_reports,
        "scenario_tag": scenario_tag,
    }


def scenarios() -> Dict[str, Dict[str, object]]:
    destinations = destinations_by_name()
    return {
        "Normal daytime trip to Parliament Hill": {
            "destination": "Parliament Hill",
            "summary": "No active reports at the exact destination; the system proceeds while avoiding absolute safety claims.",
            "expected": "Normal",
            "incidents": [
                _incident(
                    "scenario-parliament-1",
                    "Road blockage",
                    45.4274,
                    -75.6892,
                    2,
                    "Minor curb blockage reported near Rideau, away from the selected civic drop-off.",
                    18,
                    True,
                    0,
                    "normal_parliament",
                )
            ],
        },
        "Late-night uncertainty near ByWard Market": {
            "destination": "ByWard Market",
            "summary": "Several night-time reports are close enough to trigger a caution or danger-aware drop-off decision.",
            "expected": "Danger",
            "incidents": [
                _incident(
                    "scenario-byward-night-1",
                    "Harassment",
                    destinations["ByWard Market"]["latitude"] + 0.0002,
                    destinations["ByWard Market"]["longitude"] - 0.0001,
                    4,
                    "Repeated harassment near a crowded entrance.",
                    1.0,
                    True,
                    3,
                    "late_byward",
                ),
                _incident(
                    "scenario-byward-night-2",
                    "Suspicious activity",
                    45.4292,
                    -75.6920,
                    4,
                    "Multiple riders flagged the same block as unstable.",
                    1.7,
                    False,
                    4,
                    "late_byward",
                ),
                _incident(
                    "scenario-byward-night-3",
                    "Crowd surge",
                    45.4283,
                    -75.6935,
                    3,
                    "Crowd spillover into the curb lane.",
                    2.4,
                    True,
                    2,
                    "late_byward",
                ),
            ],
        },
        "Protest near destination": {
            "destination": "Parliament Hill",
            "summary": "Civic demonstration reports make exact curbside access uncertain.",
            "expected": "Caution",
            "incidents": [
                _incident(
                    "scenario-protest-1",
                    "Protest",
                    45.4239,
                    -75.7004,
                    3,
                    "Large demonstration affecting normal drop-off patterns.",
                    2.0,
                    True,
                    5,
                    "protest",
                ),
                _incident(
                    "scenario-protest-2",
                    "Road blockage",
                    45.4229,
                    -75.6992,
                    3,
                    "Temporary road closure reported by a second rider.",
                    3.1,
                    False,
                    2,
                    "protest",
                ),
            ],
        },
        "Multiple recent reports around a nightlife area": {
            "destination": "Elgin Street",
            "summary": "Reports are concentrated around a nightlife corridor and should be visible before proceeding.",
            "expected": "Caution",
            "incidents": [
                _incident(
                    "scenario-elgin-1",
                    "Poor lighting",
                    45.4164,
                    -75.6903,
                    2,
                    "Poor lighting along the last block of the walk.",
                    5,
                    False,
                    2,
                    "elgin_nightlife",
                ),
                _incident(
                    "scenario-elgin-2",
                    "Harassment",
                    45.4172,
                    -75.6914,
                    3,
                    "Unwanted approach reported outside a late-night venue.",
                    4,
                    True,
                    1,
                    "elgin_nightlife",
                ),
                _incident(
                    "scenario-elgin-3",
                    "Crowd surge",
                    45.4159,
                    -75.6898,
                    2,
                    "Crowded sidewalk reported near closing time.",
                    2.8,
                    False,
                    2,
                    "elgin_nightlife",
                ),
            ],
        },
        "One low-severity report only": {
            "destination": "Westboro",
            "summary": "A single minor report remains visible but does not exaggerate the area into a red zone.",
            "expected": "Normal",
            "incidents": [
                _incident(
                    "scenario-westboro-1",
                    "Poor lighting",
                    45.3905,
                    -75.7556,
                    1,
                    "One rider noted poor lighting on a side street.",
                    9,
                    False,
                    0,
                    "single_low",
                )
            ],
        },
        "High-severity cluster with red zone": {
            "destination": "Rideau Centre",
            "summary": "A recent cluster of serious reports makes exact drop-off inappropriate.",
            "expected": "Danger",
            "incidents": [
                _incident(
                    "scenario-rideau-red-1",
                    "Violence",
                    45.4253,
                    -75.6902,
                    5,
                    "Serious altercation reported at the curbside approach.",
                    0.8,
                    True,
                    3,
                    "rideau_red",
                ),
                _incident(
                    "scenario-rideau-red-2",
                    "Police activity",
                    45.4250,
                    -75.6895,
                    4,
                    "Police activity still visible around the entrance.",
                    1.1,
                    True,
                    2,
                    "rideau_red",
                ),
                _incident(
                    "scenario-rideau-red-3",
                    "Road blockage",
                    45.4246,
                    -75.6891,
                    4,
                    "Curb lane blocked by emergency response vehicles.",
                    1.6,
                    True,
                    2,
                    "rideau_red",
                ),
            ],
        },
        "Conflicting low-confidence situation with orange zone": {
            "destination": "uOttawa",
            "summary": "Unverified and mixed reports should create caution, not certainty.",
            "expected": "Caution",
            "incidents": [
                _incident(
                    "scenario-uottawa-conflict-1",
                    "Suspicious activity",
                    45.4228,
                    -75.6835,
                    3,
                    "Unverified report near a campus access point.",
                    2.5,
                    False,
                    2,
                    "conflicting",
                ),
                _incident(
                    "scenario-uottawa-conflict-2",
                    "Other",
                    45.4234,
                    -75.6823,
                    2,
                    "A second report describes the area as crowded but calm.",
                    3.3,
                    False,
                    1,
                    "conflicting",
                ),
                _incident(
                    "scenario-uottawa-conflict-3",
                    "Police activity",
                    45.4223,
                    -75.6840,
                    2,
                    "Small response nearby; unclear whether it affects drop-off.",
                    6.2,
                    True,
                    0,
                    "conflicting",
                ),
            ],
        },
    }
